variables:
  IMAGE_NAME: "config_server"

before_script:
  - docker info
  - chmod +x ./gradlew

stages:
  - build
  - distribute

build_docker_image:latest:
  stage: build
#  only:123

    - master
  script:
    - gradle bootRepackage
    - cp Dockerfile build/libs/
    - docker build -t jjsj/$IMAGE_NAME ./build/libs


upload_to_registry:
  stage: distribute
  only:
    - master
  script:
    - docker login -u=$REGISTRY_USERNAME -p=$REGISTRY_PASSWORD $REGISTRY_URL
    - docker tag jjsj/$IMAGE_NAME $REGISTRY_URL/$REGISTRY_GROUP/$IMAGE_NAME
    - docker push $REGISTRY_URL/$REGISTRY_GROUP/$IMAGE_NAME