server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/tyyzqmf/config-repo.git


#eureka:
#  instance:
#    hostname: localhost
#    lease-renewal-interval-in-seconds: 5
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    healthcheck:
#      enabled: true
